import React from 'react';
import './AllCategory.css';

function AllCategory() {
    return (
        <div className="content-wrap" style={{transform: "none"}}>
            <div className="container" style={{transform: "none"}}>
                <div className="main-area disable-right-sidebar" style={{transform: "none"}}>
                    <div className="category-box">
                        <ul>
                            <li>
                                <a href="#cateogry-table-cse">
                                    <span>Computer Science & Engineering</span>
                                </a>
                            </li>
                            <li>
                                <a  href="#cateogry-table-etce">
                                    <span>Electronics & Telecommunications</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-ee">
                                    <span>Electrical</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-it">
                                    <span>Information Technology</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-me">
                                    <span>Mechanical</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-che">
                                    <span>Chemical</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-ce">
                                    <span>Civil</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-arch">
                                    <span>Architecture</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-pharm">
                                    <span>Pharmacy</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-meta">
                                    <span>Metallurgy</span>
                                </a>
                            </li>
                            <li>
                                <a href="#cateogry-table-inst">
                                    <span>Intrumentation</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div className="category-tab">
                        <div id="cateogry-table-cse" className="category-table category-table-cse">
                            <div className="category-name">
                                <span>Computer Science & Engineering</span>
                            </div>
                            <div className="category-table-content">
                                <ul>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="cateogry-table-etce" className="category-table category-table-etce">
                            <div className="category-name">
                                <span>Electronics & Telecommunications</span>
                            </div>
                            <div className="category-table-content">
                                <ul>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="cateogry-table-ee" className="category-table category-table-ee">
                            <div className="category-name">
                                <span>Electrical</span>
                            </div>
                            <div className="category-table-content">
                                <ul>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="cateogry-table-it" className="category-table category-table-it">
                            <div className="category-name">
                                <span>Information Technology</span>
                            </div>
                            <div className="category-table-content">
                                <ul>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div id="cateogry-table-me" className="category-table category-table-me">
                            <div className="category-name">
                                <span>Mechanical</span>
                            </div>
                            <div className="category-table-content">
                                <ul>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                    <li>
                                        <a>Subject1</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default AllCategory
